### ISSUE TITLE
[EPIC] Develop a Wrapper for the Jitsi API

### ISSUE THREAD

**Issue by antonplagemann** [Music-Bot-for-Jitsi/jitsi-api-client#8]
> **As a** developer
> **I want** a simple api for jitsi
> **so that** I have more reusable and well-structured code.

## Description:
Develop a deno module which wraps all needed jitsi interaction and provides clean and simple methods for the jimmi backend. Use old code whenever possible, do refactoring as needed and take care of good exception handling (not yet there). Use the old code to find all methods and api calls needed for jimmi.

### 🟢 In scope:
- [ ] Music-Bot-for-Jitsi/jitsi-api-client#2
- [ ] Music-Bot-for-Jitsi/jitsi-api-client#3
- [ ] Music-Bot-for-Jitsi/jitsi-api-client#4
- [ ] Music-Bot-for-Jitsi/jitsi-api-client#5
- [ ] Music-Bot-for-Jitsi/jitsi-api-client#7

### 🔴 Not in scope:
- Everything not related to the jitsi api
- Jimmi backend stuff
- Jimmi frontend stuff

## What should be the result?
A new module in an extra repository which handles all needed interactions with the jitsi api.
